name: Nightly
on:
#  schedule:
#    cron:
#      # 05:05 UTC = 00:05 EST (01:05 EDT)
#      - 5 5 * * *
  workflow_dispatch:


jobs:
  update-nightly:
    uses: opendp/opendp/.github/workflows/update.yml@714-nightly-build
    with:
      channel: nightly
#    secrets: inherit

  release-nightly:
    needs: update-nightly
    uses: opendp/opendp/.github/workflows/release.yml@714-nightly-build
    with:
      channel: nightly
    secrets: inherit
