name: Nightly
on:
#  schedule:
#    cron:
#      # 03:55 UTC = 22:55 EST/23:55 EDT (i.e. always before midnight), so nightlies will have a sensible date
#      - 3 55 * * *
  workflow_dispatch:
    inputs:
      channel:
        description: Release Channel
        type: choice
        options:
          - nightly
          - beta
          - stable
        required: true
        default: nightly
      counter:
        description: Version Counter
        type: number
        required: false
        default: 1


jobs:
  prepare-nightly:
    uses: opendp/opendp/.github/workflows/prepare.yml@714-nightly-build
    with:
      channel: ${{ inputs.channel }}
      counter: ${{ fromJSON(inputs.counter) }}

  release-nightly:
    needs: prepare-nightly
    uses: opendp/opendp/.github/workflows/release.yml@714-nightly-build
    with:
      channel: ${{ inputs.channel }}
    secrets: inherit
