name: Nightly
on:
  schedule:
    # 03:55 UTC = 22:55 EST/23:55 EDT (i.e., always before midnight), so nightlies will have a sensible date
    - cron: '55 3 * * *'
  workflow_dispatch:

jobs:
  release:
    uses: opendp/opendp/.github/workflows/release.yml@714-nightly-build
    with:
      channel: nightly
      counter: 2
      fake: true
