name: Nightly
on:
  schedule:
    # 03:45 UTC = 22:45 EST/23:45 EDT (i.e., always before midnight), so nightlies will have a sensible date
    - cron: '45 3 * * *'
  workflow_dispatch:
    inputs:
      counter:
        description: Version Counter
        type: number
        required: false
#        default: 10  # Set counter > 1 for manual runs, so they won't block later scheduled run.

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - name: Get last run
        id: get_last_run
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: GET /repos/${{ github.repository }}/actions/workflows/nightly.yml/runs?per_page=1&status=completed

      - name: Parse last run
        id: parse_last_run
        env:
          SHA: ${{ fromJson(steps.get_last_run.outputs.data).workflow_runs[0].head_sha }}
        run: |
          echo "LAST=$SHA CURRENT=${{ github.sha }}"
          echo "changed=${{ github.sha != env.SHA }}" >> $GITHUB_OUTPUT
    outputs:
      changed: ${{ steps.parse_last_run.outputs.changed }}

  release:
    needs: check
    if: ${{ fromJson(needs.check.outputs.changed) || github.event.name == 'workflow_dispatch' }}
    uses: opendp/opendp/.github/workflows/release.yml@714-nightly-build
    with:
      channel: nightly
      sync: true
      counter: ${{ fromJson(inputs.counter) || 0 }}
    secrets: inherit
