name: Prepare Channel
on:
  workflow_call:
    inputs:
      channel:
        type: string
        required: true
      counter:
        type: number
        required: false
        default: 1
  workflow_dispatch:
    inputs:
      channel:
        description: Release Channel
        type: choice
        options:
          - nightly
          - beta
          - stable
        required: true
        default: nightly
      counter:
        description: Version Counter
        type: number
        required: false
        default: 1
env:
  # Base dates on Harvard time
  TIME_ZONE: "America/New_York"

jobs:
  prepare-channel:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure git user
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          cache: pip

      - name: Install requirements
        run: pip install -r tools/requirements-release_tool.txt

      - name: Sync channel
        run: python tools/release_tool.py sync -c ${{ inputs.channel }} -u 714-nightly-build

      - name: Configure channel
        run: python tools/release_tool.py configure -c ${{ inputs.channel }} -z "$TIME_ZONE" -i ${{ inputs.counter }}

      - name: Show changes
        run: git diff

      - name: Push changes
        run: |
          git commit -a -m "Sync and configure channel"
          git push --force origin ${{ inputs.channel }}
