name: Release
on:
  workflow_call:
    inputs:
      channel:
        type: string
        required: true
      sync:
        type: boolean
        required: false
        default: false
      counter:
        type: number
        required: false
        default: 0
      fake:
        type: boolean
        required: false
        default: false
  workflow_dispatch:
    inputs:
      channel:
        description: Target Channel
        type: choice
        options:
          - nightly
          - beta
          - stable
        required: true
        default: nightly
      sync:
        description: Sync the Channel from Upstream?
        type: boolean
        required: false
        default: false
      counter:
        description: Version Counter
        type: number
        required: false
        default: 0
      fake:
        description: Fake Build?
        type: boolean
        required: false
        default: false

jobs:
  prepare:
    uses: opendp/opendp/.github/workflows/prepare.yml@714-nightly-build
    with:
      channel: ${{ inputs.channel }}
      sync: ${{ inputs.sync }}
      counter: ${{ fromJSON(inputs.counter) }}

  build:
    needs: prepare
    uses: opendp/opendp/.github/workflows/build.yml@714-nightly-build
    with:
      channel: ${{ inputs.channel }}
      fake: ${{ inputs.fake }}

  sanity-test-pre:
    needs: build
    uses: opendp/opendp/.github/workflows/sanity-test.yml@714-nightly-build
    with:
      channel: ${{ inputs.channel }}
      python_repository: local
      fake: ${{ inputs.fake }}

  publish:
    needs: [ prepare, sanity-test-pre ]
    uses: opendp/opendp/.github/workflows/publish.yml@714-nightly-build
    with:
      channel: ${{ inputs.channel }}
      date: ${{ needs.prepare.outputs.date }}
      dry_run: true
    secrets: inherit

  sanity-test-post:
    needs: publish
    uses: opendp/opendp/.github/workflows/sanity-test.yml@714-nightly-build
    with:
      channel: ${{ inputs.channel }}
      python_repository: testpypi
      fake: ${{ inputs.fake }}
